trigger:
- master

resources:
  repositories:
    - repository: AzureDevOps-Release-Pipeline
      type: github
      name: aparnaqa1998/AzureDevOps-Release-Pipeline
      endpoint: aparnaqa1998

variables:
  dockerRegistryServiceConnection: 'c19b7425-2eb4-4f79-9f19-d290afb65bd4'
  imageRepository: 'demonodeapp'
  containerRegistry: 'demonodeapp.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'demonodeapp-secret'
  vmImageName: 'ubuntu-latest'
  ACR_NAME: 'demonodeapp'

stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: Build
    displayName: Build
    pool: 
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo $ENV_ACR_PASSWORD | docker login $(ACR_NAME).azurecr.io -u $ENV_ACR_USERNAME --password-stdin
        docker build -t $(imageRepository):$(tag) .
        docker run --rm -v $(Build.SourcesDirectory)/coverage:/usr/src/app/coverage $(ACR_NAME).azurecr.io/$(imageRepository):$(tag)
        ls -la $(Build.SourcesDirectory)/coverage
        docker tag demonodeapp:$(tag) $(ACR_NAME).azurecr.io/$(imageRepository):$(tag)
        docker push $(ACR_NAME).azurecr.io/$(imageRepository):$(tag)
      displayName: 'Build and Push docker and Copy test report'
      env:
       ENV_ACR_USERNAME: $(ACR_USERNAME) # Set as secret pipeline variable
       ENV_ACR_PASSWORD: $(ACR_PASSWORD) # Set as secret pipeline variable

    - upload: manifests
      artifact: manifests

    - script: |
       FILE_PATH=$(Pipeline.Workspace)/manifests/deployment-staging.yml
       MAX_RETRIES=60
       RETRY_INTERVAL=10  # seconds
       RETRY_COUNT=0
    
       while [ ! -f "$FILE_PATH" ] && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
        echo "File $FILE_PATH not found. Waiting for $RETRY_INTERVAL seconds..."
         sleep $RETRY_INTERVAL
       RETRY_COUNT=$((RETRY_COUNT + 1))
      done
    
       if [ -f "$FILE_PATH" ]; then
        echo "File $FILE_PATH found. Proceeding with the script."
        sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment-staging.yml > $(Pipeline.Workspace)/manifests/deployment-staging.yml
        sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment.yml > $(Pipeline.Workspace)/manifests/deployment.yml
       else
        echo "File $FILE_PATH not found after $((RETRY_COUNT * RETRY_INTERVAL)) seconds. Exiting."
        exit 1
       fi
      displayName: 'Wait for file and then run script'
      env:
        containerRegistry: $(containerRegistry)
        imageRepository: $(imageRepository)
        tag: $(tag)

- stage: Deploy_Dev
  displayName: Deploy to Dev
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'releasepipeline.kube-public'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
- stage: Deploy_Staging
  displayName: Deploy to Staging
  dependsOn: Deploy_Dev

  jobs:
  - deployment: DeployToStaging
    displayName: Deploy to Staging
    pool:
      vmImage: $(vmImageName)
    environment: 'staging.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes Cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment-staging.yml
                $(Pipeline.Workspace)/manifests/service-staging.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)