apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonodeapp-dev
   labels:
    app: demonodeapp
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demonodeapp
      environment: dev
  template:
    metadata:
      labels:
        app: demonodeapp
        environment: dev
    spec:
      containers:
      - name: demonodeapp
        image: demonodeapp.azurecr.io/demonodeapp
        ports:
        - containerPort: 3000