apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonodeapp-staging
  labels:
    app: demonodeapp
    environment: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demonodeapp
      environment: staging
  template:
    metadata:
      labels:
        app: demonodeapp
        environment: staging
    spec:
      containers:
      - name: demonodeapp
        image: $(containerRegistry)/$(imageRepository):$(tag)
        ports:
        - containerPort: 3000
