apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonodeapp
   labels:
    app: demonodeapp
    environment: releasepipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demonodeapp
  template:
    metadata:
      labels:
        app: demonodeapp
    spec:
      containers:
      - name: demonodeapp
        image: demonodeapp.azurecr.io/demonodeapp
        ports:
        - containerPort: 3000