apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demonodeapp
  template:
    metadata:
      labels:
        app: demonodeapp
    spec:
      containers:
      - name: demonodeapp
        image: $(CONTAINER_REGISTRY)/$(IMAGE_REPOSITORY):$(TAG)
        ports:
        - containerPort: 3000