apiVersion: v1
kind: Service
metadata:
  name: demonodeapp-dev
  labels:
    app: demonodeapp
    environment: dev
spec:
   type: LoadBalancer
   selector:
    app: demonodeapp
    environment: dev
   ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
